### ISSUE TITLE
Game crashes at menu

### ISSUE THREAD

**Issue by aknight2015** [Rinnegatamante/d3es-vita#2]
When I start the game, with or without lights, the game crashes when it's loading menus.

**Comment by Rinnegatamante** [comment]
It doesn't.

**Comment by Peter8Franz** [comment]
hm, demo working, but full data make trouble, will make re-test and report back

**Comment by Peter8Franz** [comment]
the demo must work !

full data files has maybe Boot error, but this has nothing to do with the main menu.

**Comment by Peter8Franz** [comment]
got it to work with RAW Unzip files for Base folder, 

closed
